name: CI Banco Ingestion Engine

# 1. ¿Cuándo se va a activar el robot?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. ¿Qué va a hacer el robot dentro de su computadora virtual?
jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    # Paso A: Clonar tu repositorio dentro de la máquina de GitHub
    - name: Checkout de codigo
      uses: actions/checkout@v3

    # ======================================================================
    # ¡NUEVO ORDEN!: Primero aseguramos Java para que PySpark tenga cimientos
    # ======================================================================
    - name: Instalar Java (Requisito de Apache Spark)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Paso B: Instalar Python de forma automática
    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Paso C: Instalar herramientas de revisión (Linter) y frameworks de pruebas
    - name: Instalar Flake8 y Dependencias de Spark
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pyspark pytest

    # Paso D: El examen de sintaxis
    - name: Analizar errores de sintaxis en el Engine
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Paso F: ¡Correr tus pruebas unitarias mapeando las variables de entorno!
    - name: Ejecutar Tests Unitarios de Spark
      env:
        # Le soplamos a PySpark la ruta exacta de Java en Ubuntu de GitHub Actions
        JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64
      run: |
        pytest pipeline/